export const tableData = [
  {
    type: 'Business Address',
    isHighlighted: false,
    startingPrice: 70,
    currency: 'SGD',
    planOptions: true,
    accessType: true,
    anytimeAccessDedicatedDesk: true,
    accessToPrivateOfficeHrs: 8,
    communityEvtAccess: false,
    canBookMeetingViaMyTEC: false,
    dedicatedStorageLocker: false,
    bookingWithDiscount: false,
    otherServicesDiscount: false,
  },
  {
    type: 'Call Handling',
    isHighlighted: false,
    startingPrice: 100,
    currency: 'SGD',
    planOptions: false,
    accessType: false,
    anytimeAccessDedicatedDesk: false,
    accessToPrivateOfficeHrs: 0,
    communityEvtAccess: true,
    canBookMeetingViaMyTEC: true,
    dedicatedStorageLocker: true,
    bookingWithDiscount: true,
    otherServicesDiscount: true,
  },
  {
    type: 'hihihi',
    isHighlighted: false,
    startingPrice: 100,
    currency: 'SGD',
    planOptions: false,
    accessType: false,
    anytimeAccessDedicatedDesk: false,
    accessToPrivateOfficeHrs: 0,
    communityEvtAccess: true,
    canBookMeetingViaMyTEC: true,
    dedicatedStorageLocker: true,
    bookingWithDiscount: true,
    otherServicesDiscount: true,
  },
  {
    type: 'Business Address & Call Handling',
    isHighlighted: true,
    startingPrice: 140,
    currency: 'SGD',
    planOptions: true,
    accessType: true,
    anytimeAccessDedicatedDesk: true,
    accessToPrivateOfficeHrs: 20,
    communityEvtAccess: true,
    canBookMeetingViaMyTEC: true,
    dedicatedStorageLocker: true,
    bookingWithDiscount: true,
    otherServicesDiscount: true,
  },
]

export const tableRowConfig = [
  {
    label: 'Starting Price',
    type: 'text',
    key: 'startingPrice',
  },
  {
    label: 'Plan Options',
    type: 'tick',
    key: 'planOptions',
  },
  {
    label: 'Access Type',
    type: 'tick',
    key: 'accessType',
  },
  {
    label: '24/7 access to a dedicated desk at your chosen Centre',
    type: 'tick',
    key: 'anytimeAccessDedicatedDesk',
  },
  {
    label: 'Business hours access to a private office',
    type: 'text',
    key: 'accessToPrivateOfficeHrs',
  },
  {
    label: 'Access to TEC Community Events and Partnership Programs',
    type: 'tick',
    key: 'communityEvtAccess',
  },
  {
    label: 'Ability to book meeting rooms through MyTEC',
    type: 'tick',
    key: 'canBookMeetingViaMyTEC',
  },
  {
    label: 'Dedicated storage locker',
    type: 'tick',
    key: 'dedicatedStorageLocker',
  },
  {
    label: 'Book Meeting Room at discounted rate',
    type: 'tick',
    key: 'bookingWithDiscount',
  },
  {
    label: 'Discounted rate for other Services',
    type: 'tick',
    key: 'otherServicesDiscount',
  },
]
