export interface Pricing {
  type: string,
  isHighlighted: boolean,
  startingPrice: number,
  currency: string,
  planOptions: boolean,
  accessType: boolean,
  anytimeAccessDedicatedDesk: boolean,
  accessToPrivateOfficeHrs: 8,
  communityEvtAccess: boolean,
  canBookMeetingViaMyTEC: boolean,
  dedicatedStorageLocker: boolean,
  bookingWithDiscount: boolean,
  otherServicesDiscount: boolean,
}
